# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcinsurer_pb2 as grpcinsurer__pb2


class GRPCInsurerStub(object):
    """The insurance service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContactAndPoliciesById = channel.unary_unary(
                '/grpcinsurer.GRPCInsurer/GetContactAndPoliciesById',
                request_serializer=grpcinsurer__pb2.UserRequest.SerializeToString,
                response_deserializer=grpcinsurer__pb2.PolicyHolderResponse.FromString,
                )
        self.GetContactsAndPoliciesByMobileNumber = channel.unary_unary(
                '/grpcinsurer.GRPCInsurer/GetContactsAndPoliciesByMobileNumber',
                request_serializer=grpcinsurer__pb2.MobileNumberRequest.SerializeToString,
                response_deserializer=grpcinsurer__pb2.PolicyHolderResponse.FromString,
                )


class GRPCInsurerServicer(object):
    """The insurance service definition.
    """

    def GetContactAndPoliciesById(self, request, context):
        """Returns a policy holder and its policies by userID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactsAndPoliciesByMobileNumber(self, request, context):
        """Returns a single policyholder and its policies by MobileNumber
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCInsurerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContactAndPoliciesById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactAndPoliciesById,
                    request_deserializer=grpcinsurer__pb2.UserRequest.FromString,
                    response_serializer=grpcinsurer__pb2.PolicyHolderResponse.SerializeToString,
            ),
            'GetContactsAndPoliciesByMobileNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactsAndPoliciesByMobileNumber,
                    request_deserializer=grpcinsurer__pb2.MobileNumberRequest.FromString,
                    response_serializer=grpcinsurer__pb2.PolicyHolderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcinsurer.GRPCInsurer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCInsurer(object):
    """The insurance service definition.
    """

    @staticmethod
    def GetContactAndPoliciesById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcinsurer.GRPCInsurer/GetContactAndPoliciesById',
            grpcinsurer__pb2.UserRequest.SerializeToString,
            grpcinsurer__pb2.PolicyHolderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContactsAndPoliciesByMobileNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcinsurer.GRPCInsurer/GetContactsAndPoliciesByMobileNumber',
            grpcinsurer__pb2.MobileNumberRequest.SerializeToString,
            grpcinsurer__pb2.PolicyHolderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
