# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcinsurer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcinsurer.proto',
  package='grpcinsurer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11grpcinsurer.proto\x12\x0bgrpcinsurer\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\",\n\x13MobileNumberRequest\x12\x15\n\rmobile_number\x18\x01 \x01(\t\"+\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rmobile_number\x18\x02 \x01(\t\">\n\x06Policy\x12\x15\n\rmobile_number\x18\x01 \x01(\t\x12\x0f\n\x07premium\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\"g\n\x14PolicyHolderResponse\x12(\n\rpolicy_holder\x18\x01 \x01(\x0b\x32\x11.grpcinsurer.User\x12%\n\x08policies\x18\x02 \x03(\x0b\x32\x13.grpcinsurer.Policy2\xd8\x01\n\x0bGRPCInsurer\x12Z\n\x19GetContactAndPoliciesById\x12\x18.grpcinsurer.UserRequest\x1a!.grpcinsurer.PolicyHolderResponse\"\x00\x12m\n$GetContactsAndPoliciesByMobileNumber\x12 .grpcinsurer.MobileNumberRequest\x1a!.grpcinsurer.PolicyHolderResponse\"\x00\x62\x06proto3'
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='grpcinsurer.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpcinsurer.UserRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=59,
)


_MOBILENUMBERREQUEST = _descriptor.Descriptor(
  name='MobileNumberRequest',
  full_name='grpcinsurer.MobileNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_number', full_name='grpcinsurer.MobileNumberRequest.mobile_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=105,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='grpcinsurer.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcinsurer.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mobile_number', full_name='grpcinsurer.User.mobile_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=150,
)


_POLICY = _descriptor.Descriptor(
  name='Policy',
  full_name='grpcinsurer.Policy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_number', full_name='grpcinsurer.Policy.mobile_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='premium', full_name='grpcinsurer.Policy.premium', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='grpcinsurer.Policy.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=214,
)


_POLICYHOLDERRESPONSE = _descriptor.Descriptor(
  name='PolicyHolderResponse',
  full_name='grpcinsurer.PolicyHolderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy_holder', full_name='grpcinsurer.PolicyHolderResponse.policy_holder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policies', full_name='grpcinsurer.PolicyHolderResponse.policies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=319,
)

_POLICYHOLDERRESPONSE.fields_by_name['policy_holder'].message_type = _USER
_POLICYHOLDERRESPONSE.fields_by_name['policies'].message_type = _POLICY
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['MobileNumberRequest'] = _MOBILENUMBERREQUEST
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Policy'] = _POLICY
DESCRIPTOR.message_types_by_name['PolicyHolderResponse'] = _POLICYHOLDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'grpcinsurer_pb2'
  # @@protoc_insertion_point(class_scope:grpcinsurer.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

MobileNumberRequest = _reflection.GeneratedProtocolMessageType('MobileNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOBILENUMBERREQUEST,
  '__module__' : 'grpcinsurer_pb2'
  # @@protoc_insertion_point(class_scope:grpcinsurer.MobileNumberRequest)
  })
_sym_db.RegisterMessage(MobileNumberRequest)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'grpcinsurer_pb2'
  # @@protoc_insertion_point(class_scope:grpcinsurer.User)
  })
_sym_db.RegisterMessage(User)

Policy = _reflection.GeneratedProtocolMessageType('Policy', (_message.Message,), {
  'DESCRIPTOR' : _POLICY,
  '__module__' : 'grpcinsurer_pb2'
  # @@protoc_insertion_point(class_scope:grpcinsurer.Policy)
  })
_sym_db.RegisterMessage(Policy)

PolicyHolderResponse = _reflection.GeneratedProtocolMessageType('PolicyHolderResponse', (_message.Message,), {
  'DESCRIPTOR' : _POLICYHOLDERRESPONSE,
  '__module__' : 'grpcinsurer_pb2'
  # @@protoc_insertion_point(class_scope:grpcinsurer.PolicyHolderResponse)
  })
_sym_db.RegisterMessage(PolicyHolderResponse)



_GRPCINSURER = _descriptor.ServiceDescriptor(
  name='GRPCInsurer',
  full_name='grpcinsurer.GRPCInsurer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=322,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetContactAndPoliciesById',
    full_name='grpcinsurer.GRPCInsurer.GetContactAndPoliciesById',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_POLICYHOLDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetContactsAndPoliciesByMobileNumber',
    full_name='grpcinsurer.GRPCInsurer.GetContactsAndPoliciesByMobileNumber',
    index=1,
    containing_service=None,
    input_type=_MOBILENUMBERREQUEST,
    output_type=_POLICYHOLDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCINSURER)

DESCRIPTOR.services_by_name['GRPCInsurer'] = _GRPCINSURER

# @@protoc_insertion_point(module_scope)
